WEBHOOK_PASSPHRASE = 'setyourpassphrasehere'

DISCORD_LOGS_URL = None
DISCORD_ERR_URL = None
DISCORD_AVATAR_URL = None
DISCORD_STUDY_URL = None
DISCORD_STUDY_AVATAR_URL = None

LEVERAGE_TESTING = None
RISK_TESTING = None
API_KEY_TESTING = None
API_SECRET_TESTING = None

#please review these settings with bybit api documentation
LEVERAGE_MYBYBITACCOUNT = 50
RISK_MYBYBITACCOUNT = 5

#Testnet API Key and Secret
API_KEY_MYBYBITACCOUNT = 'UPAFznEo72Yv5FCX1n'
API_SECRET_MYBYBITACCOUNT = 'CTmisiLKyaoRwjp6MGOSs0n2BYHDMuC2G9Rx'